# Generated by Django 4.1.4 on 2024-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ezdebts_app", "0002_alter_userdata_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("test", models.CharField(max_length=100)),
            ],
        ),
    ]
