# Generated by Django 4.1.4 on 2024-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ezdebts_app", "0004_currencies_expenses_delete_testmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="code",
            field=models.CharField(
                choices=[
                    ("SGD", "Singapore Dollar"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
