# Generated by Django 4.1.4 on 2024-06-22 05:49

from django.db import migrations

def add_initial_currencies(apps, schema_editor):
    Currencies = apps.get_model('ezdebts_app', 'Currencies')
    initial_currencies = [
        {'code': 'USD', 'name': 'US Dollar', 'symbol': '$'},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': '£'},
        {'code': 'SGD', 'name': 'Singapore Dollar', 'symbol': 'SGD$'}
        # Add more currencies as needed
    ]
    for currency in initial_currencies:
        Currencies.objects.create(**currency)

class Migration(migrations.Migration):

    dependencies = [
        ("ezdebts_app", "0005_alter_currencies_code"),
    ]

    operations = [
        migrations.RunPython(add_initial_currencies)
    ]
